itp :
  program : 'blastp'
  database : 'nr'
  sequence : 'MCSRNIKISVVLFLVLIPIFAALPHNHNLSKRSNFFDLECKGIFNKTMFFRLDRICEDCYQLFRETSIHRLCKQECFGSPFFNACIEALQLHEEMDKYNEWRDTLGRK'
  evalue : 0.001
  order : 
    Diptera : 7147
    Orthoptera : 6993
    Hemiptera : 7524
    Lepidoptera : 7088
    Blattodea : 85823
  hit_list : 50
  raw_folder: 'raw'
  outfile : 'raw/raw_itp_BLAST_results.fa'
  muscleOutput : 'raw/raw_muscled_itp_BLAST_results.fa'
  itp_conserved_regions:
    cys_1 : 58
    cys_2 : 74
    cys_3 : 77
    cys_4 : 90
    cys_5 : 94
    cys_6 : 103
  output_folder: 'output'
  sorted_muscleFile : 'output/files/sorted_muscled_itp_BLAST_results.fa'
  tableFile : 'output/files/table.csv'
  weblogo : 'output/figures/weblogo.pdf'
  pymsaviz : 'output/figures/pymsaviz.pdf'


### Try and Find tachykinin
### Pubmeb, blast searhc, research paper to varify the sequence is a NO and nothing else
### Get authentc no's to test hypothesis 